---
- hosts: centosnode1
  become: True
  tasks:
    - name: Install Packages
      yum:
        name: "httpd"
        state: "present"


    - name: Start Apache Server
      service:
        name: httpd
        state: started
        enabled: True

    - name: Deploy static website
      copy:
         src: https://github.com/myleseb/JavaWebCalculator3.git
         dest: /var/www/html