---
- hosts: 13.49.46.215
  become: True
  tasks:
    - name: Install Packages
      yum:
        name: "httpd"
        state: "present"


    - name: Start Apache Server
      service:
        name: httpd
        state: started
        enabled: True

    - name: Deploy static website
      copy:
         src: src/main/webapp/index.jsp
         dest: /var/www/html
